name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0
    
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
        
    - name: Construção e push da imagem Docker
      uses: docker/build-push-action@v6.8.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          matheusduarte21/kube-news:${{github.run_number}}
          matheusduarte21/kube-news:latest
  CD:
    runs-on: ubuntu-latest
    
     steps:
      - uses: actions/checkout@v4.2.0

      - name: definindo context
      - uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.K8S_CONFIG}}

    
  
