name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0
    - name: autenticação do docker hub
    - uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    - name: construção de imagem docker
    - uses: docker/build-push-action@v6.8.0
      with:
        contexto: ./src
        file: ./src/dockerfile
        push: true
        tags:
          matheusduarte/kube-news:v1
          matheusduarte/kube-news:lastet
  
